### ISSUE TITLE
TypeError: global.shutdown is not a function

### ISSUE THREAD

**Issue by cyrsbly** [XaviaTeam/XaviaBot#12]
[Fixed]

New issue: certificate is expired.

**Comment by RFS-ADRENO** [comment]
thanks for informing us!
Any screenshots + extra details would be appreciated!

**Comment by cyrsbly** [comment]
Hello! I fixed it by restarting the replit app thrice. :'>

**Comment by RFS-ADRENO** [comment]
alright I will close this issue within half a day if nothing more...
