### ISSUE TITLE
Update the bot :>

### ISSUE THREAD

**Issue by Aybinx** [XaviaTeam/XaviaBot#14]
Please update the bot because it has been deprecated.

**Comment by RFS-ADRENO** [comment]
We are working on it, new patch release soon!

**Comment by Reygie23** [comment]
Can I Contribute for the project?

**Comment by RFS-ADRENO** [comment]
It's always nice to have people contribute to the project!

**Comment by Reygie23** [comment]
BRO HOW CAN I UPLOAD I ADD BARD CMD FOR THIS FILE

**Comment by RFS-ADRENO** [comment]
> BRO HOW CAN I UPLOAD I ADD BARD CMD FOR THIS FILE

what do you mean? You want to contribute?

**Comment by Reygie23** [comment]
yes bro

**Comment by RFS-ADRENO** [comment]
> yes bro

okay, I appreciate a lot
