### ISSUE TITLE
customize message? 

### ISSUE THREAD

**Issue by steveisalive** [XaviaTeam/XaviaBot#26]
hello can I add customize message to new upcoming DMs !

**Comment by RFS-ADRENO** [comment]
What is that? Could you provide more details about it?

**Comment by steveisalive** [comment]
it's Like Someone message me "Hello" bot reply " Hello im not available message me at wp +1xyz

**Comment by RFS-ADRENO** [comment]
oh.. you can do that by using custom plugin.
See examples [here](https://github.com/XaviaTeam/XaviaBot/tree/main/plugins/customs)
