### ISSUE TITLE
fca update please 

### ISSUE THREAD

**Issue by MBBXMESBAH** [XaviaTeam/XaviaBot#27]

**Comment by RFS-ADRENO** [comment]
hm 🤔?

**Comment by MBBXMESBAH** [comment]
Your api can't support thisCookieEditor

**Comment by RFS-ADRENO** [comment]
Yeah, and I don't plan to either. You should use [c3c-fbstate](https://github.com/c3cbot/c3c-fbstate/) instead.

**Comment by Rxji1** [comment]
> Yeah, and I don't plan to either. You should use [c3c-fbstate](https://github.com/c3cbot/c3c-fbstate/) instead.

c3c cookie expires really fast. editthiscookie took 5 days(in my case) before it expired

**Comment by RFS-ADRENO** [comment]
> > Yeah, and I don't plan to either. You should use [c3c-fbstate](https://github.com/c3cbot/c3c-fbstate/) instead.
> 
> c3c cookie expires really fast. editthiscookie took 5 days(in my case) before it expired

alright, I will test it

**Comment by MBBXMESBAH** [comment]
I don’t know my bot account can't work in your FCA  said refresh your browser but others api working can you fix that and try to fix some more api like getUserId,  markAsRead,  and add new api shareContact

**Comment by Rxji1** [comment]
> I don’t know my bot account can't work in your FCA said refresh your browser but others api working can you fix that and try to fix some more api like getUserId, markAsRead, and add new api shareContact

usual errors, your account must have been restricted before or the acc has profile lock, code auth

**Comment by MBBXMESBAH** [comment]
> > I don’t know my bot account can't work in your FCA said refresh your browser but others api working can you fix that and try to fix some more api like getUserId, markAsRead, and add new api shareContact
> 
> usual errors, your account must have been restricted before or the acc has profile lock, code auth

🙂🙂

**Comment by MBBXMESBAH** [comment]
How to fix this

**Comment by RFS-ADRENO** [comment]
> ![Screenshot_2024-09-23-19-30-53-73](https://private-user-images.githubusercontent.com/155101462/369909677-41584cd2-99de-433d-aae2-3509b76f04a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDg3NTEsIm5iZiI6MTcyNzE0ODQ1MSwicGF0aCI6Ii8xNTUxMDE0NjIvMzY5OTA5Njc3LTQxNTg0Y2QyLTk5ZGUtNDMzZC1hYWUyLTM1MDliNzZmMDRhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwMzI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjljZDIwYzFmZWY4MjA1MTBiMDg0OGQ4MTdjOTAwNzAwYmIwZDU2MDY3Y2QzYzI1ZGZhMDliOGQwMzBhNTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6L-hl9qPADI2_t6wVWyCMJXcRAT5R7wRuPSuTxqQskg) @RFS-ADRENO bro can you fix this

what is this

**Comment by MBBXMESBAH** [comment]
I use your api in goat bot show this error but some days ago can't show this error
