### ISSUE TITLE
api.editMessage

### ISSUE THREAD

**Issue by Rxji1** [XaviaTeam/XaviaBot#28]
where is api object stored at? i wanna add goatbot editMessage

**Comment by Rxji1** [comment]
@RFS-ADRENO

**Comment by Rxji1** [comment]
never mind that i found it. now i have a problem,  api.editMessage() does not work.

**Comment by RFS-ADRENO** [comment]
I believe I already added that api...

**Comment by Rxji1** [comment]
> I believe I've already added that API...

it only works if i add global. like global.api.editMessage()

**Comment by RFS-ADRENO** [comment]
> > I believe I've already added that API...
> 
> it only works if i add global. like global.api.editMessage()

then its working bro, its not about api but how the bot designed
