### ISSUE TITLE
end to end encryption kills the bot's dm

### ISSUE THREAD

**Issue by Akane7101** [XaviaTeam/XaviaBot#36]
the bot was working well for the past 2 days.. i wrote a code to add character.ai api in the dms for some extra fun..it was going well until facebook suddenly decided to enable end to end encryption.. after that the bot couldn't receive any message from dms..not from me or anyone else.. it doesn't even appear in the logs ..and yes i checked ALLOW_INBOX and it's already set to true..
anyway to fix this?

**Comment by RFS-ADRENO** [comment]
This is a known issue related to the FCA library, and I don't plan on fixing it either.
